// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCE3ctTYYS8BftNZV3qRV-Z90EnlvSsxjQ",
      authDomain: "asec-project.firebaseapp.com",
      projectId: "asec-project",
      storageBucket: "asec-project.appspot.com",
      messagingSenderId: "632783512079",
      appId: "1:632783512079:web:ba30a5511e77538e54b97a",
      measurementId: "G-PJ437M4ZVW"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRCZvCFEcFUppKkpGe_KqHAOEvY2hLNMg',
    appId: '1:632783512079:android:2f7f20142b02842954b97a',
    messagingSenderId: '632783512079',
    projectId: 'asec-project',
    storageBucket: 'asec-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCppiSy7GxIc6lphT9lpfDY1XSTQyzDQ5s',
    appId: '1:632783512079:ios:a699f1ac8e9c577754b97a',
    messagingSenderId: '632783512079',
    projectId: 'asec-project',
    storageBucket: 'asec-project.appspot.com',
    androidClientId: '632783512079-0c7k8tl5urrf21cl960kevjipdh05rps.apps.googleusercontent.com',
    iosClientId: '632783512079-oa2pgcdat79hmd8i3mpdiidd7h4503tb.apps.googleusercontent.com',
    iosBundleId: 'com.asecappcompany.asecApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCppiSy7GxIc6lphT9lpfDY1XSTQyzDQ5s',
    appId: '1:632783512079:ios:a9b433d89c2e2a2354b97a',
    messagingSenderId: '632783512079',
    projectId: 'asec-project',
    storageBucket: 'asec-project.appspot.com',
    androidClientId: '632783512079-0c7k8tl5urrf21cl960kevjipdh05rps.apps.googleusercontent.com',
    iosClientId: '632783512079-i8vb3rv5nt6rd18es636kj4l1nccac5b.apps.googleusercontent.com',
    iosBundleId: 'com.asecappcompany.asecApplication.RunnerTests',
  );
}
